services:
  traefik:
    image: traefik:v3.6.2
    container_name: traefik_proxy
    restart: unless-stopped
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # (Resolver) Settings - Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=mefenewton@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80" # Default HTTP port
      - "443:443" # Default HTTPS port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt # Certificates folder

  llm-server:
    build: ./server
    restart: unless-stopped
    expose:
      - "8000"
    env_file:
      - ./server/.env
    depends_on:
      - redis
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers" ]
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.llm.rule=Host(`bm201proje.duckdns.org`)"
      - "traefik.http.routers.llm.entrypoints=websecure"
      - "traefik.http.routers.llm.tls.certresolver=myresolver"
      - "traefik.http.services.llm.loadbalancer.server.port=8000"

  redis:
    image: redis:alpine
    container_name: redis_broker
    restart: unless-stopped
    command: redis-server --save "" --loglevel warning