services:
  traefik:
    image: traefik:v3.6.2
    container_name: traefik_proxy
    restart: unless-stopped
    networks:
      - proxy_net
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # (Resolver) Settings - Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80" # Default HTTP port
      - "443:443" # Default HTTPS port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt # Certificates folder

  websocket-server:
    build: ./server
    restart: unless-stopped
    networks:
      - proxy_net
      - internal_net
    expose:
      - "${WEB_SOCKET_PORT}"
    env_file:
      - ./.env
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${WEB_SOCKET_PORT}" ]
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - FISH_SPEECH_API_URL=http://fish-speech:8080/v1/tts
    depends_on:
      - redis
      - ollama
      - fish-speech
    
    labels:
      # Traefik Routing
      - "traefik.enable=true"
      - "traefik.http.routers.websocket-server.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.websocket-server.entrypoints=websecure"
      - "traefik.http.routers.websocket-server.tls.certresolver=myresolver"
      - "traefik.http.services.websocket-server.loadbalancer.server.port=${WEB_SOCKET_PORT}"
      # Rate Limiting Middleware
      - "traefik.http.routers.websocket-server.middlewares=ratelimit"
      - "traefik.http.middlewares.ratelimit.ratelimit.average=10"
      - "traefik.http.middlewares.ratelimit.ratelimit.burst=5"
      - "traefik.http.middlewares.ratelimit.ratelimit.period=1s"

  redis:
    image: redis:alpine3.22
    container_name: redis_broker
    restart: unless-stopped
    networks:
      - internal_net
    command: redis-server --save "" --loglevel warning --requirepass "${REDIS_PASSWORD}"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_llm
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - internal_net

  fish-speech:
    image: fishaudio/fish-speech:latest-server-cpu
    container_name: fish_speech_tts
    restart: unless-stopped
    volumes:
      - ./fish_speech_models:/app/checkpoints
    networks:
      - internal_net

volumes:
  ollama_data:

networks:
  proxy_net:
  internal_net:
    internal: true